fix missing ca-certificates
git clone was failing:

error: Problem with the SSL CA cert (path? access rights?) while accessing https://git-wip-us.apache.org/repos/asf/cloudstack.git/info/refs